name: Chile News Mailer

concurrency:
  group: news-mailer
  cancel-in-progress: false

permissions:
  contents: read

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: {}

jobs:
  mailer:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Gate by Chile time (+/-35)
        id: gate
        shell: bash
        run: |
          NOW_S=$(TZ=America/Santiago date +%s)
          TODAY=$(TZ=America/Santiago date +%Y-%m-%d)
          T_MORN=$(TZ=America/Santiago date -d "$TODAY 07:30:00" +%s)
          T_AFTER=$(TZ=America/Santiago date -d "$TODAY 17:30:00" +%s)
          PAD=2100
          in_window () { [ $1 -ge $(( $2 - PAD )) ] && [ $1 -le $(( $2 + PAD )) ]; }
          RUN=no
          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ] || in_window "$NOW_S" "$T_MORN" || in_window "$NOW_S" "$T_AFTER"; then
            RUN=yes
          fi
          echo "run=$RUN" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-python@v5
        if: ${{ steps.gate.outputs.run == 'yes' }}
        with:
          python-version: '3.11'

      - name: Install deps
        if: ${{ steps.gate.outputs.run == 'yes' }}
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install --no-cache-dir eventregistry openai; fi

      - name: Run script
        if: ${{ steps.gate.outputs.run == 'yes' }}
        env:
          ER_API_KEY:     ${{ secrets.ER_API_KEY }}
          REMITENTE:      ${{ secrets.REMITENTE }}
          DESTINATARIO:   ${{ secrets.DESTINATARIO }}
          DESTINATARIO2:  ${{ secrets.DESTINATARIO2 }}
          APP_PASSWORD:   ${{ secrets.APP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python solo_apis.py

      - name: Skipped
        if: ${{ steps.gate.outputs.run != 'yes' }}
        run: echo "Fuera de la ventana"
