name: Chile News Mailer

concurrency:
  group: news-mailer
  cancel-in-progress: true

on:
  schedule:
    # MAÑANA: 10:25 Chile (verano/invierno)
    - cron: '45 13 * * *'  # 10:25 CL en UTC-3
    - cron: '45 14 * * *'  # 10:25 CL en UTC-4
    # TARDE: 18:00 Chile (verano/invierno)
    - cron: '0 21 * * *'   # 18:00 CL en UTC-3
    - cron: '0 22 * * *'   # 18:00 CL en UTC-4
  workflow_dispatch: {}

jobs:
  mailer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Gate: sólo continuar si en Chile es 10:45 o 18:00,
      # o si el evento es manual (workflow_dispatch)
      - name: Gate by Chile time
        id: gate
        shell: bash
        run: |
          echo "Event: $GITHUB_EVENT_NAME"
          HOUR_CL=$(TZ=America/Santiago date +%H)
          MIN_CL=$(TZ=America/Santiago date +%M)
          echo "Chile time now: $HOUR_CL:$MIN_CL"

          RUN="no"
          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ] ||
             { [ "$HOUR_CL" = "10" ] && [ "$MIN_CL" = "45" ]; } ||
             { [ "$HOUR_CL" = "18" ] && [ "$MIN_CL" = "00" ]; }; then
            RUN="yes"
          fi

          echo "run=$RUN" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-python@v5
        if: ${{ steps.gate.outputs.run == 'yes' }}
        with:
          python-version: '3.11'

      - name: Install deps
        if: ${{ steps.gate.outputs.run == 'yes' }}
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt, installing minimal deps"
            pip install --no-cache-dir eventregistry openai
          fi

      - name: Run script
        if: ${{ steps.gate.outputs.run == 'yes' }}
        env:
          ER_API_KEY:       ${{ secrets.ER_API_KEY }}
          REMITENTE:        ${{ secrets.REMITENTE }}
          DESTINATARIO:     ${{ secrets.DESTINATARIO }}
          APP_PASSWORD:     ${{ secrets.APP_PASSWORD }}
          OPENAI_API_KEY:   ${{ secrets.OPENAI_API_KEY }}
        run: python solo_apis.py

      - name: Skipped (not 10:45/18:00 CL)
        if: ${{ steps.gate.outputs.run != 'yes' }}
        run: echo "Fuera de 10:45/18:00 CL; no se ejecuta el script."
