name: Chile News Mailer

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Ejecutar ahora mismo"
        required: false
        type: boolean
        default: false
  schedule:
    - cron: "0 * * * *"   # corre cada hora en UTC

concurrency:
  group: newsjob
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      ER_API_KEY: ${{ secrets.ER_API_KEY }}
      REMITENTE: ${{ secrets.REMITENTE }}
      DESTINATARIO: ${{ secrets.DESTINATARIO }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      FORCE_RUN: ${{ github.event.inputs.force }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Solo continúa a las 08:00 o 18:00 Chile, o si lo forzaste manualmente
      - name: Gate by Chile time
        id: gate
        shell: bash
        run: |
          if [[ "${FORCE_RUN}" == "true" ]]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          NOW_CL=$(TZ=America/Santiago date +'%H:%M')
          echo "Hora Chile ahora: ${NOW_CL}"
          if [[ "${NOW_CL}" == "08:00" || "${NOW_CL}" == "18:00" ]]; then
            echo "run=true" >> "$GITHUB_OUTPUT"
          else
            echo "run=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Python
        if: steps.gate.outputs.run == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        if: steps.gate.outputs.run == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run job
        if: steps.gate.outputs.run == 'true'
        run: |
          python solo_apis.py --once

      - name: Not scheduled time
        if: steps.gate.outputs.run != 'true'
        run: echo "No es 08:00/18:00 America/Santiago. Se omite."
