name: Chile News Mailer

concurrency:
  group: news-mailer
  cancel-in-progress: false   # no cancela si entran dos ticks en la misma ventana

on:
  schedule:
    - cron: '*/5 * * * *'     # despierta cada 5 minutos (UTC)
  workflow_dispatch: {}

jobs:
  mailer:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Gate por hora Chile con ventana simétrica:
      #   07:30  => 06:55 .. 08:05   (±35)
      #   17:30  => 16:55 .. 18:05   (±35)
      - name: Gate by Chile time (±35 min)
        id: gate
        shell: bash
        run: |
          echo "Event: $GITHUB_EVENT_NAME"
          NOW_S=$(TZ=America/Santiago date +%s)
          TODAY=$(TZ=America/Santiago date +%Y-%m-%d)

          T_MORN=$(TZ=America/Santiago date -d "$TODAY 07:30:00" +%s)
          T_AFTER=$(TZ=America/Santiago date -d "$TODAY 17:30:00" +%s)

          EARLY=2100   # 35 min * 60
          LATE=2100    # 35 min * 60

          in_window () {
            local now=$1; local target=$2; local early=$3; local late=$4
            [ $now -ge $((target - early)) ] && [ $now -le $((target + late)) ]
          }

          RUN="no"
          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ] \
             || in_window "$NOW_S" "$T_MORN" "$EARLY" "$LATE" \
             || in_window "$NOW_S" "$T_AFTER" "$EARLY" "$LATE"; then
            RUN="yes"
          fi

          echo "Chile time now: $(TZ=America/Santiago date +%H:%M:%S)"
          echo "run=$RUN" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-python@v5
        if: ${{ steps.gate.outputs.run == 'yes' }}
        with:
          python-version: '3.11'

      - name: Install deps
        if: ${{ steps.gate.outputs.run == 'yes' }}
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt, installing minimal deps"
            pip install --no-cache-dir eventregistry openai
          fi

      - name: Run script
        if: ${{ steps.gate.outputs.run == 'yes' }}
        env:
          ER_API_KEY:     ${{ secrets.ER_API_KEY }}
          REMITENTE:      ${{ secrets.REMITENTE }}
          DESTINATARIO:   ${{ secrets.DESTINATARIO }}
          DESTINATARIO2:  ${{ secrets.DESTINATARIO2 }}
          APP_PASSWORD:   ${{ secrets.APP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python solo_apis.py

      - name: Skipped (outside 07:30 ±35 or 17:30 ±35)
        if: ${{ steps.gate.outputs.run != 'yes' }}
        run: echo "Fuera de la ventana; no se ejecuta el script."
