name: Chile News Mailer

# Necesario para usar actions/cache/save
permissions:
  actions: write
  contents: read

concurrency:
  group: news-mailer
  cancel-in-progress: false   # no cancela si entran dos ticks en la misma ventana

on:
  schedule:
    - cron: '*/5 * * * *'     # despierta cada 5 minutos (UTC)
  workflow_dispatch: {}

jobs:
  mailer:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Gate: 08:00 y 18:00 Chile con ventana ±35 minutos
      - name: Gate by Chile time (±35 min)
        id: gate
        shell: bash
        run: |
          set -euo pipefail
          NOW_S=$(TZ=America/Santiago date +%s)
          TODAY=$(TZ=America/Santiago date +%Y-%m-%d)
          HNOW=$(TZ=America/Santiago date +%H:%M:%S)

          T_MORN=$(TZ=America/Santiago date -d "$TODAY 08:00:00" +%s)
          T_EVEN=$(TZ=America/Santiago date -d "$TODAY 18:00:00" +%s)

          WIN=$((35 * 60))  # 35 minutos en segundos

          in_window () { [ "$1" -ge $(( $2 - WIN )) ] && [ "$1" -le $(( $2 + WIN )) ]; }

          RUN="no"; WINDOW=""
          if [ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ]; then
            RUN="yes"; WINDOW="manual"
          elif in_window "$NOW_S" "$T_MORN"; then
            RUN="yes"; WINDOW="morning"
          elif in_window "$NOW_S" "$T_EVEN"; then
            RUN="yes"; WINDOW="evening"
          fi

          echo "Chile time now: $HNOW (America/Santiago)"
          echo "run=$RUN"       >> "$GITHUB_OUTPUT"
          echo "window=$WINDOW" >> "$GITHUB_OUTPUT"
          echo "date=$TODAY"    >> "$GITHUB_OUTPUT"

      # ---------- LOCK: restaurar (único step, dinámico) ----------
      - name: Restore lock
        if: ${{ steps.gate.outputs.run == 'yes' && steps.gate.outputs.window != 'manual' }}
        id: lock_restore
        uses: actions/cache/restore@v4
        with:
          path: .cache-lock/${{ steps.gate.outputs.window }}
          key: mailer-lock-${{ steps.gate.outputs.window }}-${{ steps.gate.outputs.date }}

      # Decidir si correr considerando el lock
      - name: Decide with lock
        id: decide
        shell: bash
        run: |
          RUN="${{ steps.gate.outputs.run }}"
          WIN="${{ steps.gate.outputs.window }}"
          HIT="${{ steps.lock_restore.outputs.cache-hit }}"
          OK="no"
          if [ "$RUN" = "yes" ]; then
            if [ "$WIN" = "manual" ]; then
              OK="yes"           # manuales ignoran el lock
            elif [ "$HIT" != "true" ]; then
              OK="yes"           # primer tick de la ventana
            fi
          fi
          echo "ok=$OK" >> "$GITHUB_OUTPUT"

      # Crear y guardar lock (bloquea ticks siguientes de la misma ventana)
      - name: Create lock dir & file
        if: ${{ steps.decide.outputs.ok == 'yes' && steps.gate.outputs.window != 'manual' }}
        run: |
          mkdir -p ".cache-lock/${{ steps.gate.outputs.window }}"
          echo "locked at $(date -u)Z" > ".cache-lock/${{ steps.gate.outputs.window }}/LOCK"

      - name: Save lock
        if: ${{ steps.decide.outputs.ok == 'yes' && steps.gate.outputs.window != 'manual' }}
        uses: actions/cache/save@v4
        with:
          path: .cache-lock/${{ steps.gate.outputs.window }}
          key: mailer-lock-${{ steps.gate.outputs.window }}-${{ steps.gate.outputs.date }}

      # ---------- Sólo corre si ok == yes ----------
      - uses: actions/setup-python@v5
        if: ${{ steps.decide.outputs.ok == 'yes' }}
        with:
          python-version: '3.11'

      - name: Install deps
        if: ${{ steps.decide.outputs.ok == 'yes' }}
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt, installing minimal deps"
            pip install --no-cache-dir eventregistry openai
          fi

      - name: Run script
        if: ${{ steps.decide.outputs.ok == 'yes' }}
        env:
          ER_API_KEY:     ${{ secrets.ER_API_KEY }}
          REMITENTE:      ${{ secrets.REMITENTE }}
          DESTINATARIO:   ${{ secrets.DESTINATARIO }}
          DESTINATARIO2:  ${{ secrets.DESTINATARIO2 }}
          APP_PASSWORD:   ${{ secrets.APP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python solo_apis.py

      - name: Skipped (outside window or locked)
        if: ${{ steps.decide.outputs.ok != 'yes' }}
        run: echo "Saltado: fuera de 08:00/18:00 ±35 min o ya hubo un envío en esta ventana."
