name: Chile News Mailer

concurrency:
  group: news-mailer
  cancel-in-progress: true

on:
  schedule:
    # MAÑANA (Chile) — 09:45 CL
    - cron: '45 12 * * *'  # 09:45 CL cuando Chile está en UTC-3 (verano)
    - cron: '45 13 * * *'  # 09:45 CL cuando Chile está en UTC-4 (invierno)
    # TARDE (Chile) — 18:00 CL
    - cron: '0 21 * * *'   # 18:00 CL (UTC-3)
    - cron: '0 22 * * *'   # 18:00 CL (UTC-4)
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Forzar ejecución aunque no sea exactamente 09:45/18:00 CL'
        required: false
        type: boolean
        default: false
      hours_back_override:
        description: 'Opcional: forzar ventana (número de horas, p.ej. 6)'
        required: false
        type: string
        default: ''

jobs:
  mailer:
    runs-on: ubuntu-latest
    env:
      ER_API_KEY: ${{ secrets.ER_API_KEY }}
      REMITENTE: ${{ secrets.REMITENTE }}
      DESTINATARIO: ${{ secrets.DESTINATARIO }}
      DESTINATARIO2: ${{ secrets.DESTINATARIO2 }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # deja vacío si no usas IA
      HOURS_BACK_OVERRIDE: ${{ inputs.hours_back_override }}

    steps:
      - uses: actions/checkout@v4

      # Gate: solo corre si en Chile es 09:45 o 18:00 exacto (o si force_run=true)
      - name: Gate by Chile time
        id: gate
        run: |
          FORCE="${{ inputs.force_run }}"
          HOUR_CL=$(TZ=America/Santiago date +%H)
          MIN_CL=$(TZ=America/Santiago date +%M)
          echo "Hora Chile: $HOUR_CL:$MIN_CL"
          if [ "$FORCE" = "true" ]; then
            echo "run=yes" >> $GITHUB_OUTPUT
            exit 0
          fi
          if { [ "$HOUR_CL" = "09" ] && [ "$MIN_CL" = "45" ]; } || { [ "$HOUR_CL" = "18" ] && [ "$MIN_CL" = "00" ]; }; then
            echo "run=yes" >> $GITHUB_OUTPUT
          else
            echo "run=no" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-python@v5
        if: steps.gate.outputs.run == 'yes'
        with:
          python-version: '3.11'

      - name: Install deps
        if: steps.gate.outputs.run == 'yes'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        if: steps.gate.outputs.run == 'yes'
        run: python solo_apis.py

      - name: Skipped (not 09:45/18:00 CL)
        if: steps.gate.outputs.run != 'yes'
        run: echo "⛔ Fuera de 09:45/18:00 CL y sin force_run: no se ejecuta el script."
